apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    mode: rwx-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # This will be replaced by the deployment script with actual NFS server IP
    server: NFS_SERVER_IP
    path: /
  mountOptions:
    - nfsvers=4.2

