apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: storage-demo
  labels:
    app: storage-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: storage-demo:latest
  source:
    type: Git
    git:
      uri: https://github.com/jaypoulz/two-node-storage-demo.git
      ref: main
    contextDir: /
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
  - type: ImageChange
