apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-demo-reader
  labels:
    app: storage-demo
    role: reader
spec:
  replicas: 2  # Two reader pods on different nodes for high availability
  selector:
    matchLabels:
      app: storage-demo
      role: reader
  template:
    metadata:
      labels:
        app: storage-demo
        role: reader
    spec:
      containers:
      - name: reader
        image: image-registry.openshift-image-registry.svc:5000/storage-test/storage-demo:latest
        imagePullPolicy: Always
        env:
        - name: ROLE
          value: "reader"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt/shared
          readOnly: true  # Reader mounts as read-only
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: linstor-shared-storage
          readOnly: true  # Reader accesses PVC as read-only
      # Anti-affinity to ensure readers run on DIFFERENT nodes from each other
      # This demonstrates that replicated storage can be accessed from multiple nodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - reader
            topologyKey: kubernetes.io/hostname
