apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-demo-writer
  labels:
    app: storage-demo
    role: writer
spec:
  replicas: 1  # Single writer pod
  selector:
    matchLabels:
      app: storage-demo
      role: writer
  template:
    metadata:
      labels:
        app: storage-demo
        role: writer
    spec:
      containers:
      - name: writer
        image: image-registry.openshift-image-registry.svc:5000/storage-test/storage-demo:latest
        imagePullPolicy: Always
        env:
        - name: ROLE
          value: "writer"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt/shared
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: linstor-shared-storage
